name: exercise_element
description: "the component of Anywhere Abs that describes the exercise."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  exercise_icons:
    path: ../exercise_icons
  freezed_annotation: ^2.4.4
  go_router: ^14.0.0
  provider: ^6.1.2
  foundation: ^0.0.5
  json_annotation: ">=4.9.0 <5.0.0"

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/


